### ISSUE TITLE
Hero Image

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginMediaCenterManualEntries#20]
If there is a "top image" that should override all other images. Right now if you have a top image and a YouTube video. The YouTube video is showing. Maybe it's because I added the YouTube video first?

**Comment by lakshaydulani** [comment]
Hello Ian,
As we have seen in the demos, we were overriding the Video player over the top image always. If we override the top image, are we going to show the video once the user clicks on Watch link? And while watching, the top image will be hidden or the video player will be shown beneath the top image?

**Comment by ianblair44** [comment]
I see what you mean. Let's just leave it as is for now.
