### ISSUE TITLE
APP MEDIA CENTER - A date is forced on the entry, but in most cases will be wrong.

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/pluginMediaCenterManualEntries#35]
A date is being forced on manual entries, but in most cases will be wrong.

For example, if someone is adding a video that was taken two weeks before the date they are actually adding it, it will be the wrong date.

It is very rare that someone will upload an item on the same day it was created.

**Comment by ianblair44** [comment]
How is the date supposed to be generated then?

**Comment by nathankeating** [comment]
For manual entries, this should be a field so that the app owner can specify the date of that actual video/article/etc.

**Comment by lakshaydulani** [comment]
Fixed. Added a date input named "Media Date" at the bottom. Please review.

**Comment by ianblair44** [comment]
Can we make it default to the current date and then they can change it? Just so it isn't a bunch more work for the user.

**Comment by nathankeating** [comment]
That would be fine. As long as they can change it.

**Comment by lakshaydulani** [comment]
The media date is default set to the current date now.

**Comment by nathankeating** [comment]
Does this only occur if there are no spaces? Or does it occur just with long title names in general?
