### ISSUE TITLE
APP MEDIA CENTER - Top image issues

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/pluginMediaCenterManualEntries#36]
The following issues are occurring with the top image in the item details page:

- The top image should zoom so that it takes up the entire height and width of the div (whichever is lesser so that there is no white/blank space.
- The top image should show until the user clicks “watch”, then it will be replaced with the video. Currently, the top image does not show if there is a video.

**Comment by ianblair44** [comment]
![screen shot 2015-09-30 at 9 42 06 pm](https://cloud.githubusercontent.com/assets/2794086/10213051/dd8d19fc-67bc-11e5-9d52-6a3033b42e29.png)

**Comment by ianblair44** [comment]
Thumbnail at the top should be 100% width and 100% height. @lakshaydulani 

![screen shot 2015-09-30 at 9 47 14 pm](https://cloud.githubusercontent.com/assets/2794086/10213064/1a1e4a94-67bd-11e5-8344-22b26aa145bc.png)

**Comment by lakshaydulani** [comment]
Fixed for the Item 1 layout. The layout 2 doesn't have stretched top image.
Please review.
