### ISSUE TITLE
Issue with plugin structure, where to put my dev-dependencies

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/pluginMediaCenterManualEntries#4]
For maintainable code i want use bower where i can define our dependencies and dev-dependencies. So that in future we do have to face version issue. How i can structure it. So that we can separate dev-dependencies from original plugin source code.

**Comment by DanielHindi** [comment]
Please give me an example of dev dependencies you have. Is it for unit testing, analytics, tracing ...etc?

**Comment by deepakshrma** [comment]
For npm modules:
"devDependencies": {
    "chai": "^3.0.0",
    "jasmine-core": "^2.3.4",
    "karma": "^0.12.37",
    "karma-chai": "^0.1.0",
    "karma-jasmine": "^0.3.6",
    "karma-mocha": "^0.2.0",
    "karma-phantomjs-launcher": "^0.2.0",
    "mocha": "^2.2.5",
    "phantomjs": "^1.9.17"
  }
//For bower 
 "dependencies": {
    "angular": "~1.4.2",
    "angular-mocks": "~1.4.2"
  }
Please visit below given url for more clarity of the structure, Sample demo app
https://github.com/deepakshrma/testing-jasmine-karma/tree/master/Step4-Services/finish

**Comment by DanielHindi** [comment]
you can just add another folder next to control and widget called [tests] which should be ignored everywhere

**Comment by deepakshrma** [comment]
Done! Please check it.
