### ISSUE TITLE
Content Not Showing Up

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginMediaCenterManualEntries#41]
See the images in the carousel and WYSIWYG. 

Nothing is showing up on the widget site. 

![screen shot 2015-09-22 at 10 00 16 am](https://cloud.githubusercontent.com/assets/2794086/10025398/e638b014-6110-11e5-835e-62bb1718af75.png)

**Comment by vineetasharma** [comment]
@ianblair44  Fixed the issue. Please Check it.
