### ISSUE TITLE
Audio Player Background is white

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginMediaCenterManualEntries#43]
This seems to have regressed. 

The background scrolls as well. There should be no way for it to scroll. 

![screen shot 2015-09-30 at 9 42 06 pm](https://cloud.githubusercontent.com/assets/2794086/10213037/aab7d828-67bc-11e5-83af-e87f72b87fd6.png)

**Comment by lakshaydulani** [comment]
@ianblair44 I have made the background black. I was not able to replicate the background scrolling issue.
