### ISSUE TITLE
When you first create a widget data doesn't show

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginMediaCenterManualEntries#44]
This only happens the first time you create a widget instance. You have to then refresh the page for data to show up. 

![screen shot 2015-10-12 at 3 07 58 pm](https://cloud.githubusercontent.com/assets/2794086/10440061/13dfe1da-70f3-11e5-9264-c87b994f2a00.png)

**Comment by lakshaydulani** [comment]
Fixed. Please check.
