### ISSUE TITLE
Audio Player Background is missing image

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginMediaCenterManualEntries#49]
See the mockup, the audio image should be blurred in the background. 

![screen shot 2015-10-13 at 8 33 17 pm](https://cloud.githubusercontent.com/assets/2794086/10474305/0c4b61cc-71ea-11e5-9554-16b13be5d25b.png)

**Comment by lakshaydulani** [comment]
Fixed. Please review.
