### ISSUE TITLE
Design issue with plugin

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/pluginMediaCenterManualEntries#5]
@JDM555, Hi john same issue with this plug in too. Could you fix the same.
![error with pull request](https://cloud.githubusercontent.com/assets/7682731/9208251/0cc66024-4090-11e5-8717-7beda65e7d4d.png)

**Comment by jdm135** [comment]
@deepakshrma Yes. This is the same issue. I have just pushed my latest code. Please pull my code for peoplePlugin and SDK to test again.

**Comment by deepakshrma** [comment]
Looks awesome :-) :+1:
