### ISSUE TITLE
Navigation Not Implimented

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginMediaCenterManualEntries#51]
https://github.com/BuildFire/sdk/wiki/How-to-use-Navigation

When you go into an item, the back button should take you to the list view.

**Comment by lakshaydulani** [comment]
Fixed. Please review.

**Comment by ianblair44** [comment]
The back button should take you to the launcher plugin on the list view. 

buildfire.navigation.navigateHome ()

Closes out the current plugin and navigates to the Home Plugin.

**Comment by lakshaydulani** [comment]
Fixed.
