### ISSUE TITLE
Clicking back in the nav bar takes you to your home plugin instead of the previous page

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/pluginMediaCenterManualEntries#57]
Clicking back in the nav bar takes you to your home plugin instead of the previous page

**Comment by lakshaydulani** [comment]
It takes to the home when the user is on the landing page. Otherwise it takes the user to the previous page. Please update the plugin on int and review. Its working fine.

**Comment by nathankeating** [comment]
confirmed
