### ISSUE TITLE
Top Image does not show up when inside an item if you have a video

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/pluginMediaCenterManualEntries#60]
The top Image does not show up when inside an item if you have included a video URL.

What should happen is that when a user enters an item, the top image should be visible. Then when the user clicks "watch", the image would go away and in it's place would be the embedded video which should automatically start playing.

**Comment by lakshaydulani** [comment]
Fixed. Please review. Clicking on Watch toggles the video on the top.
